name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.19', '1.20', '1.21.x' ]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up GO
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}